# yml file based on https://github.com/pandoc/pandoc-action-example
name: compile docs

on: release

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          # this will also include README.md
          echo "FILELIST=$(printf '"%s" ' ./markdown/*.md)" >> $GITHUB_ENV
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/volume_I4.pdf ${{ env.FILELIST }}
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/volumne_I4.docx -t docx ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
